 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
 jobs:
  test:
    description: Setup and run application tests
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "TaskManager/TaskManager.UI/TaskManager.UI.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "TaskManager/TaskManager.UI/TaskManager.UI.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          #command: dotnet.exe build --configuration Release
          command: dotnet.exe publish -c Release -r win10-x64
      - run:
          name: Compress Artifacts
          command: tar -cvzf TaskManager.tar C:\Users\circleci\project\TaskManager.UI\bin\Release\netcoreapp3.1\win10-x64\artifact
      - store_artifacts:
          path: C:\Users\circleci\project\TaskManager.UI\bin\Release\netcoreapp3.1\win10-x64\artifact
 workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test   